// Subjects per academic level with their price multipliers.
// Different subjects within a level have different complexity, hence different pricing.
// Used by the price calculator and order form.

export const SUBJECTS_BY_LEVEL: Record<string, string[]> = {
  "high-school": [
    "Mathematics",
    "Sciences (Biology, Chemistry, Physics)",
    "English / Literature",
    "History / Social Studies",
    "Foreign Languages",
    "Computer Science / IT",
    "Arts / Music / Design",
    "AP / IB / Honors",
  ],
  "college": [
    "Mathematics / Statistics",
    "Sciences (Biology, Chemistry, Physics)",
    "English / Humanities",
    "Business / Accounting",
    "Computer Science / IT",
    "Engineering / Technical",
    "Nursing / Health Sciences",
    "Arts / Design / Music",
  ],
  "undergraduate": [
    "Mathematics / Statistics",
    "Sciences (Biology, Chemistry, Physics)",
    "Humanities (English, History, Philosophy)",
    "Business / Economics / Finance",
    "Computer Science / IT",
    "Engineering (Mechanical, Civil, Electrical)",
    "Social Sciences (Psychology, Sociology)",
    "Arts / Design / Architecture",
    "Law / Pre-law",
    "Medicine / Pre-med / Nursing",
  ],
  "masters": [
    "STEM (Math, Physics, Engineering)",
    "Life Sciences (Biology, Chemistry)",
    "Humanities (English, History, Philosophy)",
    "Business / MBA / Finance",
    "Computer Science / Data Science",
    "Law / LLM",
    "Medicine / Public Health / Nursing",
    "Arts / Design / Architecture / Music",
  ],
  "doctoral": [
    "STEM (Math, Physics, Engineering)",
    "Life Sciences (Biology, Chemistry)",
    "Humanities (English, History, Philosophy)",
    "Business / DBA / Finance",
    "Computer Science / Data Science",
    "Law / JD",
    "Medicine / PharmD / Public Health",
    "Psychology / PsyD",
    "Education / EdD",
  ],
  "research": [
    "STEM Research",
    "Life Sciences Research",
    "Humanities Research",
    "Social Sciences Research",
  ],
  "professional": [
    "Postgraduate Diploma",
    "Postgraduate Certificate",
    "Graduate Diploma",
    "Graduate Certificate",
  ],
};

export const SUBJECT_MULTIPLIERS: Record<string, Record<string, number>> = {
  "high-school": {
    "Mathematics": 0.9,
    "Sciences (Biology, Chemistry, Physics)": 0.95,
    "English / Literature": 0.85,
    "History / Social Studies": 0.85,
    "Foreign Languages": 0.9,
    "Computer Science / IT": 1.0,
    "Arts / Music / Design": 0.9,
    "AP / IB / Honors": 1.1,
  },
  "college": {
    "Mathematics / Statistics": 1.0,
    "Sciences (Biology, Chemistry, Physics)": 1.0,
    "English / Humanities": 0.9,
    "Business / Accounting": 1.0,
    "Computer Science / IT": 1.05,
    "Engineering / Technical": 1.1,
    "Nursing / Health Sciences": 1.1,
    "Arts / Design / Music": 0.95,
  },
  "undergraduate": {
    "Mathematics / Statistics": 1.0,
    "Sciences (Biology, Chemistry, Physics)": 1.05,
    "Humanities (English, History, Philosophy)": 0.95,
    "Business / Economics / Finance": 1.0,
    "Computer Science / IT": 1.1,
    "Engineering (Mechanical, Civil, Electrical)": 1.15,
    "Social Sciences (Psychology, Sociology)": 0.95,
    "Arts / Design / Architecture": 1.0,
    "Law / Pre-law": 1.1,
    "Medicine / Pre-med / Nursing": 1.15,
  },
  "masters": {
    "STEM (Math, Physics, Engineering)": 1.0,
    "Life Sciences (Biology, Chemistry)": 1.0,
    "Humanities (English, History, Philosophy)": 0.95,
    "Business / MBA / Finance": 1.0,
    "Computer Science / Data Science": 1.05,
    "Law / LLM": 1.05,
    "Medicine / Public Health / Nursing": 1.1,
    "Arts / Design / Architecture / Music": 1.0,
  },
  "doctoral": {
    "STEM (Math, Physics, Engineering)": 1.0,
    "Life Sciences (Biology, Chemistry)": 1.0,
    "Humanities (English, History, Philosophy)": 0.95,
    "Business / DBA / Finance": 1.0,
    "Computer Science / Data Science": 1.05,
    "Law / JD": 1.05,
    "Medicine / PharmD / Public Health": 1.1,
    "Psychology / PsyD": 1.0,
    "Education / EdD": 0.95,
  },
  "research": {
    "STEM Research": 1.0,
    "Life Sciences Research": 1.0,
    "Humanities Research": 0.95,
    "Social Sciences Research": 0.95,
  },
  "professional": {
    "Postgraduate Diploma": 1.0,
    "Postgraduate Certificate": 1.0,
    "Graduate Diploma": 1.0,
    "Graduate Certificate": 1.0,
  },
};

export const DEADLINE_OPTIONS = [
  { value: "standard", label: "Standard", multiplier: 1.0, description: "Regular turnaround (5-14 days)" },
  { value: "urgent", label: "Urgent", multiplier: 1.5, description: "Faster turnaround (2-3 days)" },
];

export const LEVEL_MULTIPLIERS: Record<string, number> = {
  "high-school": 0.5,
  "college": 0.7,
  "undergraduate": 0.85,
  "masters": 1.0,
  "doctoral": 1.5,
  "research": 1.3,
  "professional": 1.2,
};
